<?php
/**
 * MailnJoy Email validation API
 * @param $email
 * @param $validationType
 * @return bool
 */
function verifyEmail(string $email, string $validationType = 'simple', bool $job = false): bool
{
    $curl = curl_init();

    curl_setopt_array($curl, [
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => $email,
        CURLOPT_URL => "https://api.mailnjoy.com/v2/unitary/?type=" . $validationType,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_CONNECTTIMEOUT => 5,
        CURLOPT_TIMEOUT => 15,
        CURLOPT_HTTPHEADER => [
            "mailnjoy-id: " . config('hybris.mailnjoy_id'),
            "mailnjoy-secret: " . config('hybris.mailnjoy_secret'),
            "Content-Type: text/plain",
        ],
    ]);

    try
    {
        $raw = curl_exec($curl);

        if ($raw === false)
        {
            if($job) {
                throw new \RuntimeException('MailNJoy curl error: ' . curl_error($curl));
            } else {
                return false;
            }
        }

        $decoded = json_decode($raw);

        if (!is_object($decoded) || !isset($decoded->unitaryCheck) || !is_object($decoded->unitaryCheck))
        {
            if($job) {
                throw new \RuntimeException('MailNJoy invalid JSON');
            } else {
                return false;
            }
        }

        $api = $decoded->unitaryCheck;

    }
    catch (\Throwable $e)
    {
        if($job) {
            throw new \RuntimeException('MailNJoy Fetch Error: '.$e->getMessage(), 0, $e);
        } else {
            return false;
        }
    }
    finally
    {
        curl_close($curl);
    }

    $status = (isset($api->status)?$api->status:'INVALID');
    $autogenerated = (isset($api->attributs->autogenerated->value)?$api->attributs->autogenerated->value:false);
    $disposable = (isset($api->attributs->disposable->value)?$api->attributs->disposable->value:false);
    $suspect = (isset($api->attributs->suspect->value)?$api->attributs->suspect->value:false);
    $spamtrap = (isset($api->attributs->spamtrap->value)?$api->attributs->spamtrap->value:false);
    $catchall = (isset($api->attributs->catchall->value)?$api->attributs->catchall->value:false);

    if($status != 'VALID' || ($status == 'VALID' && ($disposable || $spamtrap || $suspect)) || (($status == 'VALID' && $autogenerated) && ($disposable || $catchall || $suspect)) || (($status == 'VALID' && $catchall) && ($disposable || $spamtrap || $suspect))) {
        return false;
    }

    return true;
}
